### PR TITLE
added FunctionRelatedField

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
I know we could achieve this usually through a property.
But sometimes is useful to be able to do this.

**Comment by reinbach** [comment]
Why not make use of the `SerializerMethodField()` for these scenarios?

**Comment by domdinicola** [comment]
Yeah, I guess that can be the right solution.
If was only a tentative to keep the it dry without the need to create a method

**Comment by domdinicola** [comment]
@reinbach like this we would be able to combine it with a many=True and source param, inorder to do something like this:

action_taken = FunctionRelatedField(source='comments', many=True, read_only=True,
                                        callable_function=comment_export_function)



check ticket ch9019

**Comment by reinbach** [comment]
Couldn't that ticket be handled with something like the following;

```
action_taken = serializers.SerializerMethodField()

def get_action_taken(self, obj):
  return "; ".join(["{} ({}): {}".format(c.user, c.date, c.comment) for c in obj.comments.all()])
```

**Comment by domdinicola** [comment]
yes agree, this would only be a "shortcut"

**Comment by domdinicola** [comment]
@reinbach so for you this is a no?

**Comment by reinbach** [comment]
@domdinicola If this shortcut is helpful for you, then I say go ahead and implement it.

**Pull request merged**
